# Generated by Django 2.1.1 on 2018-10-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181003_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='library_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LibraryEvent'),
        ),
    ]
