# Generated by Django 2.1.1 on 2018-10-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181011_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryevent',
            name='book_title',
            field=models.CharField(default='I am a book', max_length=100),
            preserve_default=False,
        ),
    ]
